### ISSUE TITLE
UnsupportedClassVersionError when tried to run as Java Application

### ISSUE THREAD

**Issue by anilkulkarni87** [jrphub/TestCaseAutomation#1]
java.lang.UnsupportedClassVersionError: com/automation/module/ProcessMain : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
Exception in thread "main"

**Comment by jrphub** [comment]
Hi Anil,

The error explains,

java.lang.UnsupportedClassVersionError happens because of a higher JDK
during compile time and lower JDK during runtime.

I think, the project uses jdk 1.7
IN eclipse project=>Proerties=>java compiler; set "the compiler compliance
level" to the version 1.7 (install jdk1.7 if not installed)

If any problem , let me know :)

Cheers,
Jyotiranjan

On 27 January 2015 at 03:15, anilkulkarni87 notifications@github.com
wrote:

> java.lang.UnsupportedClassVersionError: com/automation/module/ProcessMain
> : Unsupported major.minor version 51.0
> at java.lang.ClassLoader.defineClass1(Native Method)
> at java.lang.ClassLoader.defineClassCond(Unknown Source)
> at java.lang.ClassLoader.defineClass(Unknown Source)
> at java.security.SecureClassLoader.defineClass(Unknown Source)
> at java.net.URLClassLoader.defineClass(Unknown Source)
> at java.net.URLClassLoader.access$000(Unknown Source)
> at java.net.URLClassLoader$1.run(Unknown Source)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> Exception in thread "main"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jrphub/TestCaseAutomation/issues/1.

## 

Regards
Jyoti Ranjan Pattnaik

**Comment by anilkulkarni87** [comment]
Can you please let me know if this includes the module for email as well> like emailing the report? If yes under which class is it?

**Comment by jrphub** [comment]
Hi Anil,

The reporting module is not present in the project, but the report can be
generated easily by using the _scenarios_ instance (which is an object of
bean class Scenarios.java
https://github.com/jrphub/TestCaseAutomation/blob/master/src/com/automation/beans/Scenarios.java
) present in
_ProcessTestCases.java._
So, generate report first, then you can mail following any template you
want. The email module is not present in the project.
But once, report is generated you can email it following this blog article

https://jyotiranjanpattnaik.wordpress.com/2013/01/05/313/

Regards,
Jyotiranjan

On 29 January 2015 at 02:05, anilkulkarni87 notifications@github.com
wrote:

> Can you please let me know if this includes the module for email as well>
> like emailing the report? If yes under which class is it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jrphub/TestCaseAutomation/issues/1#issuecomment-71910648
> .

## 

Regards
Jyoti Ranjan Pattnaik
